create_driver servo_motor_driver
set_sw_property hw_class_name SERVO_HW_IP
set_sw_property version 1
set_sw_property min_compatible_hw_version 1.0
add_sw_property bsp_subdirectory drivers
add_sw_property c_source HAL/src/soft_drivers.c
add_sw_property include_source HAL/inc/servo_motor_drivers.h
add_sw_property include_source HAL/inc/soft_drivers.h
add_sw_property supported_bsp_type HAL